algo = input('Digite algo: ')
print('O tipo primitivo desse valor é {}.'.format(type(algo)))
print('Só tem virgulas? ', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabética? ', algo.isalpha())
print('É alfanumérico? ', algo.isalnum())
print('Está em maiúsculas ?', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
